//! Exception Handling in JavaScript âš¡

/* function test (){
    try{
        // alerth("hello");
        var number = "Mohit Raj";
        var x = number.toUpperCase();
        alert(x);
        


    } catch(err){
        document.getElementById('res').innerText = err;
    }
}  */

// function test() {
//     try {
//       const number = "Mohit Raj";
//       const x = number.toUpperCase();
  
//       const resElement = document.getElementById('res');
//       if (resElement) {
//         resElement.textContent = x;
//       } else {
//         console.error("Element with id 'res' not found");
//       }
//     } catch (err) {
//       console.error(err);
//       const resElement = document.getElementById('res');
//       if (resElement) {
//         resElement.textContent = err.message;
//       }
//     }
//   }

//! Javascript try catch throw statement 

